trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --configuration production
  displayName: 'Install dependencies and build Angular app'

# Replace 'your-project-name' with the actual name inside the 'projects' in angular.json
- task: CopyFiles@2
  inputs:
    Contents: 'dist/devops-demo/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy built Angular app to staging directory'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'angular-app'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'

# Deploy the build artifact to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1 (2b0fc391-9b97-4f81-927f-718122a18912)'  # Replace with your actual service connection name
    appName: 'azureDemoAnkit'  # Replace with your actual Azure app name
    package: '$(Build.ArtifactStagingDirectory)/angular-app/$(Build.BuildId).zip'  # Ensure this path is correct
  displayName: 'Deploy to Azure Web App'
