trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --configuration production
  displayName: 'Install dependencies and build Angular app'

- task: CopyFiles@2
  inputs:
    Contents: 'dist/devops-demo/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/angular-app'
  displayName: 'Copy built Angular app to staging directory'

# Zip the output
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/angular-app'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/angular-app/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Zip Angular app for deployment'

# Publish zip artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/angular-app'
    ArtifactName: 'angular-app'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'

# Deploy zip to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1 (2b0fc391-9b97-4f81-927f-718122a18912)'
    appName: 'azureDemoAnkit'
    package: '$(Build.ArtifactStagingDirectory)/angular-app/$(Build.BuildId).zip'
  displayName: 'Deploy to Azure Web App'
